const actionConstants = {
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_REQUEST: "GET_TODO_REQUEST",
  GET_TODO_FAILED: "GET_TODO_FAILED",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  ADD_TODO_FAILED: "ADD_TODO_FAILED",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
};

export default actionConstants;
